### ISSUE TITLE
Improve Semantic Kernel Module

### ISSUE THREAD

**Issue by Josephrp** [Tonic-AI/DataTonic#16]
# Summary

We need to align or produce a semantic kernel module/planner that takes the taskweaver outputs to produce something aligned with the Statement of Work for autogen to use.

# Tasks 

1. produce one or more planners that will use taskweaver plugins and generate the below as an output.

(Pre Phase 1) - Statement Of Work:
Image
(Pre Phase 1 - Statement of Work)
Introduction

    Overview: Brief description of the client's organization and the context of the engagement.
    Purpose of the SoW: Clarification of the document's intent and its role as a guiding agreement.

Project Objectives and Scope

    Objectives: Clear and specific goals the project aims to achieve.
    Scope of Work: Detailed description of the services and tasks to be performed. This section delineates what is included and, just as importantly, what is not included in the engagement.

Project Approach and Methodology

    Methodology: Explanation of the methodologies, frameworks, or strategies the consulting team will employ.
    Phases of Work: Breakdown of the project into phases or milestones, each with specific tasks and objectives.

Deliverables

    List of Deliverables: Detailed list of expected outputs, reports, presentations, tools, or models to be provided.
    Quality Standards: Description of the standards or criteria against which the deliverables will be assessed. 
Timeline

    Project Timeline: Detailed timeline of the project, including start and end dates, phase durations, and key milestones.
    Review Points: Scheduled points for reviewing progress and adjusting plans as necessary.

*6. Roles and Responsibilities

    Consulting Team Composition: Names and roles of the consultants involved.
    Client Responsibilities: Specific tasks or inputs required from the client, such as data provision, key personnel involvement, etc.**

Pricing and Payment Terms

    Fee Structure: Details on how the consulting fees are structured - fixed fee, time and materials, etc.
    Payment Schedule: Timeline and conditions for payments.

Confidentiality, Legal, and Ethical Considerations

    Confidentiality Clauses: Terms ensuring the confidentiality of shared information.
    Legal and Compliance Aspects: Adherence to relevant laws and industry regulations.
    Ethical Standards: Commitment to maintaining high ethical standards during the engagement.

Terms and Conditions

    Contractual Terms: General terms including contract duration, termination conditions, dispute resolution mechanisms, etc.
    Amendment Process: Process for making changes to the SoW.

Signatures

    Sign-off: Signatures from authorized representatives of both the consulting firm and the client.

**Comment by Zochory** [comment]
https://learn.microsoft.com/en-us/semantic-kernel/prompts/your-first-prompt?tabs=Csharp
A ressource for prompting

**Comment by Josephrp** [comment]
improve the Semantic Kernel Planner
