### ISSUE TITLE
interface for DataTonic

### ISSUE THREAD

**Issue by Josephrp** [Tonic-AI/DataTonic#2]
we have a few options :-)

**Comment by Josephrp** [comment]
will re-open as appropriate

**Comment by Zochory** [comment]
@Josephrp can you accept the Linear integration ? 
https://linear.app/qredence/join/675575ebc14645dc18c1050401c04fb4?s=4 if interested to join it linear side

**Comment by Josephrp** [comment]
i have accepted the invitation , but the space is empty :-) in general, i do reccommend : check the issues and jump in + keep it there more than "project management" , but i happily follow your process 🚀
