### ISSUE TITLE
SQL Database Design

### ISSUE THREAD

**Issue by Josephrp** [Tonic-AI/DataTonic#22]
Based on the provided semantic_kernel_module.py and its integration with TaskWeaverSQLIntegration, we can design a database schema that effectively supports the data processing and storage requirements for generating a Statement of Work (SoW) document. The schema should accommodate storing results from TaskWeaver's processing steps and potentially other relevant data for the SoW.

#Database Schema Design

### Results Table:

This table will store the outputs from each processing step in the TaskWeaver.
```sql
Copy code
CREATE TABLE IF NOT EXISTS results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    section TEXT NOT NULL,
    details TEXT,
    processed_content TEXT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
id: A unique identifier for each record.
section: The section of the SoW document this record belongs to (e.g., 'introduction', 'project_objectives_scope').
details: The raw details or inputs provided for processing this section.
processed_content: The output from the TaskWeaver processing step.
timestamp: The date and time when the record was created or processed.
Project Details Table (Optional):
```
If you want to store the initial project details separately:
```sql
Copy code
CREATE TABLE IF NOT EXISTS project_details (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    section TEXT NOT NULL,
    details TEXT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
project_id: Identifier for the project.
section: Corresponding section in the SoW.
details: Raw details of the project for this section.
```
### Implementing the Schema in TaskWeaverSQLIntegration
In the initialize_database method of TaskWeaverSQLIntegration, implement the SQL commands to create these tables:

```python
Copy code
def initialize_database(self):
    self.db_connection.execute('''
        CREATE TABLE IF NOT EXISTS results (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            section TEXT NOT NULL,
            details TEXT,
            processed_content TEXT,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
        );
    ''')
    # Uncomment the below code to create the project_details table
    # self.db_connection.execute('''
    #     CREATE TABLE IF NOT EXISTS project_details (
    #         id INTEGER PRIMARY KEY AUTOINCREMENT,
    #         project_id TEXT NOT NULL,
    #         section TEXT NOT NULL,
    #         details TEXT,
    #         timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
    #     );
    # ''')
    self.db_connection.commit()
```
### Data Insertion and Retrieval
Modify process_and_store_data and retrieve_data_for_planner methods to insert and fetch data according to this schema.
Ensure that every insertion into the results table includes the section name, raw details, processed content, and timestamp.

### Conclusion
This database schema provides a structured way to store and manage the data required for generating a SoW document. It accommodates the storage of both raw inputs and processed outputs, ensuring that all necessary information for each section of the SoW is readily available and well-organized.

**Comment by Josephrp** [comment]
the above is simply a GPT example, we need to align this with our use case and probably pass it more in taskweaver than in semantic-kernel

**Comment by Zochory** [comment]
https://linear.app/qredence/issue/QRE-15/sql-database-design#comment-c4e5f4f6

**Comment by h0lybyte** [comment]
For schema generation and maintenance, I am using a combination of Drizzle and Diesel.

Main schema (drizzle) would be here -> https://github.com/Tonic-AI/kbve/blob/main/apps/api/src/db/schema.ts
Rust schema via Diesel would be here -> https://github.com/Tonic-AI/kbve/blob/main/packages/kbve/src/schema.rs

Actual SQL would then be placed in the migrations -> database folder. 
https://github.com/Tonic-AI/kbve/tree/main/migrations/database

With Drizzle, you can export out to Zod as well, so that helps with front-end validation via React.
Diesel can help with raw SQLX for backend validation, also proto buffer validation, ect..

**Comment by Josephrp** [comment]
so currently the schemas i guess ... dont exist , and we're meant to be processing and collating a lot of heterogeneous information, like client profiles and balance sheets, so i dont really know what you have in mind but i would rate this a very high priority high impact task @h0lybyte @GoldenWind8

**Comment by Josephrp** [comment]
WIP in Task Weaver Branches
