### ISSUE TITLE
install & update codebase dotenv to manage sensitive user information

### ISSUE THREAD

**Issue by twilwa** [Tonic-AI/DataTonic#24]
python-dotenv is the package you want, then regex for 'api' to replace should do it

**Comment by Josephrp** [comment]
this's a good issue, please break it up into PRs for autogen , semantic kernel and taskweaver accordingly. Each library has a different way to load configurations, the most optimal way is to use the OAI_CONFIG_LIST if possible, and if not analogous methods, but whatever method we have must work with the library in the libraries' own way.

i'll keep this open in the mean time to facilitate a global branch if you go that way , it would be great to document what each module requires in their separate issues or in here. If you want to push/pull one at a time please make a branch inside the open issues for autogen, sk, tw, etc.
