### ISSUE TITLE
Interface : Retool as a choice for the front-end solution

### ISSUE THREAD

**Issue by Zochory** [Tonic-AI/DataTonic#26]
Reason : 

- Very easy to go live, perfect for MVP at minimum
- Have a self-hosting choice
- I have a Business Account so pretty much all the features
- Has builtin database, third party provider in it (Postgres, Mongo, OpenAI etc etc etc)
- Styling possible 
- Can handle developer logics, workflows, APIs, ...
- Is fit for the project in term of back-end<>LLM<>front-end

Example of an interface (more a wireframe, since it just for showing you 
https://www.loom.com/share/385defc10f7b48db96471175902f983d?sid=f02cc527-2008-4811-9940-709cb07f19a1

![image](https://github.com/Tonic-AI/DataTonic/assets/60674042/21c2fd62-264f-4b78-8711-434485b9eec2)
![image](https://github.com/Tonic-AI/DataTonic/assets/60674042/60658e3f-5e21-4e84-9f57-de5952433f0d)

**Comment by Josephrp** [comment]
resolved.
