### ISSUE TITLE
Supabase for User Authentication provider 

### ISSUE THREAD

**Issue by Zochory** [Tonic-AI/DataTonic#27]
I would suggest Supabase as it's easy, fast, free, combo well with any framework/tool
Ability to have Email + password login, Googe OAuth, Github OAuth etc...
Since it's Postgres (has also python, js ... client)  and open source, is very flexible

**Comment by Josephrp** [comment]
it's much smarter to put features that do not add any core functions or produce something different in the outcomes, to the roadmap
