### ISSUE TITLE
Add Semantic Kernel Connector for Gemini

### ISSUE THREAD

**Issue by Zochory** [Tonic-AI/DataTonic#28]
https://github.com/Gravicode/SKGemini
Would be a way to integrate properly Gemini to Semantic Kernel

**Comment by Josephrp** [comment]
please add issues to their existing issues if required

**Comment by Josephrp** [comment]
https://github.com/Jenscaasen/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.Mistral

check this which is the ongoing connector for SK , it's important if we decide to use gemini inside of semantic-kernel to only use this one .

the big problem is that it's a lot of extra work!
