### ISSUE TITLE
trulens eval: weaviate vs neo4j w/ imagebind multimodal vector db to ground Gemini

### ISSUE THREAD

**Issue by twilwa** [Tonic-AI/DataTonic#39]
this sounded like a fun one
opened this for my evals plan so ppl can see what i'm doing, i'll solo this unless someone actively wants to help

https://github.com/weaviate-tutorials/multimodal-workshop/blob/main/2-multimodal/1-multimedia-search-complete.ipynb
https://github.com/tomasonjo/blogs/blob/master/llm/neo4j_llama_multimodal.ipynb
are the notebooks
@MN-Noor i might have q's for ya if i get stuck trying to implement the eval pipeline on these puppies, but i'll take a crack at it myself first unless something looks real fun to jump in on :P

**Comment by Josephrp** [comment]
please use messengers to text message eachother
